# Generated by Django 5.2.17 on 2026-10-01 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('bank', 'Bank')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(blank=True, upload_to='payment_channels/')),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('canvas_json_snapshot', models.JSONField(blank=True, default=dict)),
                ('preview_image', models.ImageField(blank=True, upload_to='order_previews/')),
                ('status', models.CharField(choices=[('job_request', 'Job Request'), ('pending_edit', 'Pending Edit'), ('production', 'Production'), ('completed', 'Completed')], default='job_request', max_length=20)),
                ('agreed_total', models.DecimalField(blank=True, decimal_places=2, help_text='Set by admin/accounting. Null until priced.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='designs.design')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_file', models.FileField(blank=True, upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.paymentchannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
