# Generated by Django 5.2.17 on 2026-10-01 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new_lead', 'New Lead'), ('order_confirmed', 'Order Confirmed'), ('design_review', 'Design Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('lost', 'Lost')], default='new_lead', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
