# Generated by Django 5.2.17 on 2026-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit_accounting',
            field=models.BooleanField(default=False, help_text='Only meaningful for staff. Admins always can edit accounting.'),
        ),
    ]
