# Generated by Django 5.2.17 on 2026-10-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('design_created', 'Design created'), ('design_submitted', 'Design submitted'), ('design_revised', 'Design revised'), ('design_approved', 'Design approved'), ('order_confirmed', 'Order confirmed'), ('phase_moved', 'Phase moved'), ('lead_stage_changed', 'Lead stage changed')], max_length=32),
        ),
    ]
