# Generated by Django 5.2.17 on 2026-10-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_activitylog_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='garment_color',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black'), ('gray', 'gray'), ('navy', 'navy'), ('red', 'red'), ('royal', 'royal'), ('green', 'green'), ('yellow', 'yellow'), ('orange', 'orange'), ('maroon', 'maroon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='design',
            name='garment_template',
            field=models.CharField(blank=True, choices=[('tee', 'tee'), ('polo', 'polo'), ('jersey', 'jersey'), ('hoodie', 'hoodie')], max_length=100),
        ),
    ]
